import { TASK_STATUS, type GenerationTask } from "./types";

const seedTimestamp = Date.now();
const minute = 60_000;

const minutesAgo = (value: number) =>
  new Date(seedTimestamp - value * minute).toISOString();

export const generationTaskSeed: GenerationTask[] = [
  {
    id: "gen-task-001",
    type: "image",
    status: TASK_STATUS.running,
    prompt: "Неоновый киберпанк-город под дождем, вид сверху",
    model: {
      id: "midjourney-v6",
      name: "Midjourney",
      version: "v6",
    },
    progress: 64,
    credits: 80,
    estimatedDurationSec: 30,
    createdAt: minutesAgo(18),
    updatedAt: minutesAgo(1),
    queuedAt: minutesAgo(18),
    startedAt: minutesAgo(3),
  },
  {
    id: "gen-task-002",
    type: "video",
    status: TASK_STATUS.running,
    prompt: "Короткий ролик: стеклянный поезд проходит через арктическую станцию",
    model: {
      id: "runway-gen-3",
      name: "Runway",
      version: "Gen-3",
    },
    progress: 27,
    credits: 240,
    estimatedDurationSec: 220,
    createdAt: minutesAgo(16),
    updatedAt: minutesAgo(1),
    queuedAt: minutesAgo(16),
    startedAt: minutesAgo(5),
  },
  {
    id: "gen-task-003",
    type: "text",
    status: TASK_STATUS.queued,
    prompt: "Сценарий welcome-сообщения для нового пользователя ERA2",
    model: {
      id: "gpt-5",
      name: "GPT",
      version: "5",
    },
    progress: 0,
    credits: 12,
    estimatedDurationSec: 18,
    createdAt: minutesAgo(14),
    updatedAt: minutesAgo(14),
    queuedAt: minutesAgo(14),
  },
  {
    id: "gen-task-004",
    type: "audio",
    status: TASK_STATUS.queued,
    prompt: "Спокойный эмбиент для экрана ожидания генерации",
    model: {
      id: "udio-v1",
      name: "Udio",
      version: "v1",
    },
    progress: 0,
    credits: 110,
    estimatedDurationSec: 145,
    createdAt: minutesAgo(12),
    updatedAt: minutesAgo(12),
    queuedAt: minutesAgo(12),
  },
  {
    id: "gen-task-005",
    type: "image",
    status: TASK_STATUS.queued,
    prompt: "Минималистичная иконка подписки с мягким оранжевым свечением",
    model: {
      id: "flux-pro",
      name: "Flux",
      version: "Pro",
    },
    progress: 0,
    credits: 60,
    estimatedDurationSec: 35,
    createdAt: minutesAgo(10),
    updatedAt: minutesAgo(10),
    queuedAt: minutesAgo(10),
  },
  {
    id: "gen-task-006",
    type: "video",
    status: TASK_STATUS.queued,
    prompt: "Продуктовый тизер: интерфейс очереди плавно оживает на темном фоне",
    model: {
      id: "pika-2",
      name: "Pika",
      version: "2.0",
    },
    progress: 0,
    credits: 210,
    estimatedDurationSec: 190,
    createdAt: minutesAgo(8),
    updatedAt: minutesAgo(8),
    queuedAt: minutesAgo(8),
  },
  {
    id: "gen-task-007",
    type: "text",
    status: TASK_STATUS.done,
    prompt: "Пять вариантов заголовка для страницы очереди генераций",
    model: {
      id: "claude-sonnet-4",
      name: "Claude",
      version: "Sonnet 4",
    },
    progress: 100,
    credits: 16,
    estimatedDurationSec: 24,
    createdAt: minutesAgo(42),
    updatedAt: minutesAgo(39),
    queuedAt: minutesAgo(42),
    startedAt: minutesAgo(41),
    finishedAt: minutesAgo(39),
    result: {
      fileName: "queue-headlines.txt",
      mimeType: "text/plain",
    },
  },
  {
    id: "gen-task-008",
    type: "image",
    status: TASK_STATUS.done,
    prompt: "Абстрактный фон warm coal с тонкими медными линиями",
    model: {
      id: "stable-diffusion-xl",
      name: "Stable Diffusion",
      version: "XL",
    },
    progress: 100,
    credits: 45,
    estimatedDurationSec: 40,
    createdAt: minutesAgo(55),
    updatedAt: minutesAgo(51),
    queuedAt: minutesAgo(55),
    startedAt: minutesAgo(54),
    finishedAt: minutesAgo(51),
    previewUrl: "/placeholder.svg",
    result: {
      fileName: "warm-coal-background.png",
      mimeType: "image/png",
    },
  },
  {
    id: "gen-task-009",
    type: "audio",
    status: TASK_STATUS.failed,
    prompt: "Динамичный звук уведомления для завершенной генерации",
    model: {
      id: "elevenlabs-sfx",
      name: "ElevenLabs",
      version: "SFX",
    },
    progress: 48,
    credits: 70,
    estimatedDurationSec: 95,
    createdAt: minutesAgo(34),
    updatedAt: minutesAgo(29),
    queuedAt: minutesAgo(34),
    startedAt: minutesAgo(32),
    finishedAt: minutesAgo(29),
    error: {
      code: "model_unavailable",
      message: "Модель временно недоступна",
    },
  },
  {
    id: "gen-task-010",
    type: "text",
    status: TASK_STATUS.canceled,
    prompt: "Черновик FAQ про кредиты и лимиты генераций",
    model: {
      id: "gpt-4o-mini",
      name: "GPT",
      version: "4o mini",
    },
    progress: 12,
    credits: 8,
    estimatedDurationSec: 20,
    createdAt: minutesAgo(24),
    updatedAt: minutesAgo(22),
    queuedAt: minutesAgo(24),
    startedAt: minutesAgo(23),
    finishedAt: minutesAgo(22),
  },
];
